### PR TITLE
Unified Builds of jsapi and jsglue

### LINKED ISSUE #435: Windows Builds Fail when `clang-cl` Flags are added to `CXXFLAGS`
The root issue here is that bindgen uses `clang` (not `clang-cl`) on windows, and on unrecognised flags, it fails. Upon adding `CXXFLAGS="/clang:-flto=thin /clang:-fuse-ld=lld-link"`, the below code automatically adds it to bindgen's flags as well. As `/clang:` flags are only recognised by `clang-cl`, there is no way for `cc` and the `makefile.cargo` to receive the `CXXFLAGS` but not bindgen.
https://github.com/servo/mozjs/blob/c7fb1b8d029ba80443da92fbdadb650fcdb493a7/mozjs-sys/build.rs#L334-L338

There are a few possible approaches:
1. If a flag starts with `/clang:` on windows, do not add it to bindgen.
2. Add a separate `BINDGEN_CXXFLAGS` variable for bindgen's flags.

As said earlier, the root issue is the usage of `clang`, which means this error may not be just from `/clang:` flags but almost any `cl` flag. Hence, I would suggest the latter approach.

For a concrete example of the failure, see <https://github.com/Redfire75369/spiderfire/actions/runs/7112793006/job/19363443030#step:6:18053>, where a `libclang error` is caused.

In the event it matters for updating whatever depends on it, #136 was the original PR where this behaviour was introduced.

### PR DESCRIPTION
**Pull request by redfire75369**
Unified flags, as well as the usage of `cc` and `bindgen` for `jsapi` and `jsglue`.
Reorganised the `build.rs` primarily for the unification, but there are some changes in ordering and module organisation.
I'm not 100% sure on the ordering, so if you would like, that can be changed as well.

Resolves #435 through the removal of `-x c++` and addition of `--driver-mode=cl` on windows from the invocations of `bindgen`. Replaces #437.

Note the failures in `aarch64-pc-windows-msvc` are due to an error in llvm 18 https://github.com/llvm/llvm-project/pull/93235 (see https://github.com/rust-lang/rust-bindgen/issues/2842 also). LLVM 18.1.8 is installed on github actions runners for windows-2022. I have tested that LLVM 19 works correctly on spiderfire.

### CODE REVIEW

**Comment by sagudev** [comment]
> Note the failures in aarch64-pc-windows-msvc are due an error in llvm 18 https://github.com/llvm/llvm-project/pull/93235 (see https://github.com/rust-lang/rust-bindgen/issues/2842 also). LLVM 18.1.8 is installed on github actions runners for windows-2022. I have tested that LLVM 19 works correctly on spiderfire.

We should pin LLVM to 19 in CI then (but only for aarch64), this is not used in servo so it should not be a problem there.

File: mozjs-sys/build.rs [hunk 1]
```diff
@@ -56,11 +47,7 @@ const SM_TARGET_ENV_VARS: &'static [&'static str] = &[
     "OBJCOPY",
 ];
 
-const EXTRA_FILES: &'static [&'static str] = &["makefile.cargo", "src/jsapi.cpp"];
```
Comment (sagudev) [inline mozjs-sys/build.rs:59]: I think we only need makefile.cargo as cc should emit `cargo:rerun-if-changed` for us.

File: mozjs-sys/build.rs [hunk 2]
```diff
@@ -696,434 +556,593 @@ impl ParseCallbacks for CustomCargoCallbacks {
     }
 }
 
-mod jsglue {
-    use crate::CustomCargoCallbacks;
-    use std::env;
-    use std::path::{Path, PathBuf};
+/// The version of moztools we expect.
+#[cfg(windows)]
+const MOZTOOLS_VERSION: &str = "4.0";
```
Comment (sagudev) [inline mozjs-sys/build.rs:561]: I think we should keep this on top of file.

File: mozjs-sys/build.rs [hunk 3]
```diff
@@ -696,434 +556,593 @@ impl ParseCallbacks for CustomCargoCallbacks {
...
+            match self {
+                BuildTarget::JSApi => jsapi::MODULE_RAW_LINES,
+                BuildTarget::JSGlue => jsglue::MODULE_RAW_LINES,
+            }
+        }
+    }
+
+    mod jsapi {
+        /// JSAPI types for which we should implement `Sync`.
+        pub(crate) const UNSAFE_IMPL_SYNC_TYPES: &'static [&'static str] = &[
```
Comment (sagudev) [inline mozjs-sys/build.rs:699]: can we just inline uses and remove `mod`s

**Comment by sagudev** [comment]
This makes everything much clear and consistent!

Before landing this we should make companion PR to servo to be sure we don't brake anything there.

File: mozjs-sys/build.rs (hunk 3 above)
Comment (Redfire75369) [reply mozjs-sys/build.rs:699]: This is possible, but I thought it would look weird if the functions had super long bodies that was just a constant.

**Comment by sagudev** [comment]
I think this will need mozjs-sys bump.

**Comment by Redfire75369** [comment]
Should it be a minor or patch bump?

**Comment by jdm** [comment]
https://github.com/servo/servo/pull/37240

**Comment by jdm** [comment]
All servo builds passed, so we should be good to merge here.

**Review by jdm — APPROVED** [review]
