### PR TITLE
Fixed Windows Compilation with LLVM 17

### LINKED ISSUE #410: Build Failure on Windows with LLVM 17.0.1
```bat
  error: unsupported option '-G' for target 'x86_64-pc-windows-msvc'
  # ...
  thread 'main' panicked at 'Unable to generate bindings to jsglue: ClangDiagnostic("error: unsupported option '-G' for target 'x86_64-pc-windows-msvc' ...)
```
Not sure why this happens, but updating from 16.0.6 caused this issue.

Full Log with `-v`: <https://paste.gg/p/redfire/0ec149108e884db08c0bd9ca052645a7>

### PR DESCRIPTION
**Pull request by Redfire75369**
Fixes #410

### CODE REVIEW

File: mozjs/build.rs [hunk 1]
```diff
@@ -82,9 +82,9 @@ fn main() {
 
     if msvc {
         builder = builder.clang_args([
+            "-fms-compatibility",
             &format!("-FI{}", confdefs_path.to_string_lossy()),
             "-DWIN32",
-            "-GR-",
```
Comment (sagudev) [inline mozjs/build.rs:87]: Is removing this still needed?

Comment (Redfire75369) [reply mozjs/build.rs:87]: I believe so. Either way, `-fms-compatibility` effectively includes that by default.

Comment (sagudev) [reply mozjs/build.rs:87]: I would keep it to make things more explicit.

Comment (Redfire75369) [reply mozjs/build.rs:87]: Since we're compiling for Windows with MSVC, I'd say just having `-fms-compatibility` is fine. If anything further breaks, that's a clang thing.

Moreover, this lines up with `mozjs-sys/build.rs`, which also uses this flag.

Comment (sagudev) [reply mozjs/build.rs:87]: I think (not sure) that those options were historically sourced from SM, and there is -GR- specified explicitly, that's why I would keep it. @jdm might know this more specifically.

**Review by sagudev — APPROVED** [review]

**Comment by sagudev** [comment]
Last commit wasn't merged but I think `-fms-compatibility` is also good so I wouldn't revert it.
